- index.js
> CIO-8 Revert padding

- README.md
> CIO-15 Add license information and link to npm account

- index.js
- package-lock.json
- package.json
- utils/git.js
> CIO-1 Add unhandled rejection listener

- index.js
- utils/git.js
> CIO-18 Swap header names

- utils/git.js
> CIO-3 Add fetch functions to fetch and prune users default fetch branch

- utils/git.js
> CIO-14 Update documention for git utils. Mark formatRefs as private function

- index.js
- utils/git.js
> CIO-25 Reverse clearItems and fetch branch function calls to clear data before promise is called.

- README.md
- index.js
- utils/git.js
> CIO-9 Update popup style

- utils/git.js
> CIO-32 Add quiet flag to fetch command so nothing is printed.

- index.js
- utils/git.js
> CIO-4 Update branch path logic to display combined remote/branch

- index.js
- package-lock.json
- utils/git.js
> CIO-21 Change current selected branch method

- index.js
> CIO-43 Remove debug and warning options from screen.

- index.js
- utils/helpText.js
> CIO-31 Add help dialogue

- utils/git.js
> CIO-42 Remove fetch on getRemotes

- .prettierrc
- index.js
- utils/git.js
- utils/helpText.js
- utils/interface.js
- utils/theme.json
> CIO-45 Move blessed dialogues to util file.

- index.js
- utils/interface.js
#53 Test windows compatibility - Change path resolutions
> CIO-53 Update paths to use path.resolve()

- README.md
> CIO-7 Readme update

- README.md
- index.js
- utils/git.js
- utils/helpText.js
- utils/interface.js
- utils/utils.js
> CIO-59 Add Tabs Feature

- utils/interface.js
> CIO-69 Set question height to 5 lines instead of a relative 20 percent

- README.md
- index.js
- package-lock.json
- package.json
- utils/helpText.js
- utils/interface.js
> CIO-55 Add jack-cli dependency

- index.js
- package-lock.json
- package.json
> CIO-95 Hit the road jack

- lib/utils/interface.js
- package-lock.json
- src/utils/interface.js
> CIO-89 Squeaky Clean Scrolling

- README.md
> CIO-121 npm Shield Should Exist In README

- README.md
Reverts jwu910/check-it-out#122
> Revert "CIO-121 npm Shield Should Exist In README"

- lib/utils/git.js
- src/utils/git.js
> CIO-129 Big Data Bad Data

- lib/app.js
- lib/utils/git.js
- src/app.js
- src/utils/git.js
> CIO-85 Path less traveled

- docs/index.html
> CIO-140 replace npm badges with github fork and star

- docs/index.html
- docs/main.css
> CIO-154-coffee

- package-lock.json
- package.json
- src/redux/store.js
> CIO-149 Setup store

- src/redux/actions.js
> CIO-150-actions

- .gitignore
- dist/app.js
- dist/utils/git.js
- dist/utils/helpText.js
- dist/utils/interface.js
- dist/utils/utils.js
- package-lock.json
- package.json
> Release 0.7.9

- README.md
- package.json
> CIO-167 Twitter

- package-lock.json
- package.json
> CIO-184 Pocket Lint

- .travis.yml
- README.md
> CIO-103 Refinement

- package-lock.json
- package.json
> CIO-190 Remove Redux

- .github/stale.yml
> CIO-187 Stale Bot

- src/app.js
- src/utils/git.js
> CIO-200 Regression

- src/app.js
- src/utils/git.js
> CIO-56 Groupies

- package.json
> CIO-207 update package.json homepage URL

- README.md
> CIO-221-keyboards

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
> Release 0.9.1

- index.html
👋 I noticed the issue link for the Windows Compatibility Issue was missing the actual repo.
🚀 This small pr fixes that :)
Happy Coding! 💻
> Fixes Windows compatability issue link

- .github/pull_request_template.md
Fixes #268 
Creating a PR Template to make the PR workflow a little neater.
This template would need to be present in the default branch in order for it to trigger when someone opens a PR
Change should help prevent issues with Danger (and other automated checks going forward).
Closes #268
> CIO-268 Create a PR template to aid in workflow

- .prettierignore
- package-lock.json
- package.json
> CIO-271 Add format script with prettier on all js files

- index.html
Fixes #294 
I added the fork ribbon anchor tab to the top of the body section in index.html
This change was made to make it easier for interested parties to fork the repository easier on github.
- [ x] I have read the **CONTRIBUTING** document.
> Added fork ribbon to gh-pages

- package-lock.json
> CIO-0-Security

- README.md
Fixes #310 
Adding LGTM badge image via <a> element.
Using LGTM to track introduction of code smells and tech debt. Adding badge to readme to demonstrate that.
> CIO-310 adding LGTM Badge to ReadMe

- README.md
Fixes #311 
Added the CodeClimate badge as provided in the issue description to the README.md 
Added new badge to the README.md
Using codeCoverage to keep track of this projects code maintainability, lets add the badge to our Readme.
- [ x] New feature (non-breaking change which adds functionality)
- [ x] I have read the **CONTRIBUTING** document.
> CIO-311 Added codeclimate badge

- CHANGELOG.md
- src/utils/git.js
Fixes #313
To DRY up code
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I have read the **CONTRIBUTING** document.
> CIO-313 fix similar code

- index.html
Also updated the current node version blog as well
Fixes #{issue}
> feat: Updating minimum supported node version

- index.html
Fixes #389 
I added Metatag Markup for Facebook, Twitter, and other Social Media platforms.
When sharing "Checkit.club", there isn't a set preview photo.
> CIO-389 Update Metatags for Social Media Preview (RH)

- index.html
> Fixes link for Fork Ribbon

- .github/workflows/npmpublish.yml
> Create npm publish action

- src/app.js
*--version* output does not have a line break, this changes adds a line break to the output
#460
> fix: 🐛 Adds line break to --version output

- README.md
- package-lock.json
- package.json
- src/app.js
Fixes #459 
copy highlighted branch name to clipboard.
used key `y` for copying(vim-style)
> CIO-459 copy highlighted branch name to clipboard

- src/utils/helpText.js
Fixes #470 
add Copy highlighted item to helpText
BREAKING CHANGE: 🧨 No
> fix: 🐛 add copy(y) to helpText

- README.md
- package-lock.json
- package.json
- src/app.ts
- src/index.ts
- src/types.ts
- src/utils/git.ts
- src/utils/interface.ts
- src/utils/state.ts
Hey @jwu910! Thought I'd give this one a shot. I gave all the features a quick test and it seems to be working well, but please feel free to pick it apart and double-check everything. Let me know if you have any questions or concerns. Thanks!
This migrates the remaining `js` files to use Typescript. It also adds a dedicated type file.
#492
> #492 Typescript migration to send

- CODE_OF_CONDUCT.md
No issue, just updating email address
> docs: update coc email

- CONTRIBUTING.md
no issue, update email in contributing doc
> chore: update contributing email
